source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.3'
use_frameworks!

xcodeproj 'NightClubApp'

pod 'SWXMLHash', '~> 2.0.0'
pod 'Alamofire', '~> 3.0'
pod 'AlamofireImage', '~> 2.0'
pod 'Soundcloud'
pod 'KDEAudioPlayer'